apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        pushgateway:
          enabled: false
        alertmanager:
          ingress:
            enabled: true
            hosts:
              - alertmanager.k3s.zremal.org
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        grafana:
          ingress:
            enabled: true
            hosts:
              - grafana.k3s.zremal.org
        prometheus:
          thanosIngress:
            enabled: true
            hosts:
              - thanos-gateway.k3s.zremal.org
          ingress:
            enabled: true
            hosts:
              - prometheus.k3s.zremal.org
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.3.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true